// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Parking.DataAccess.Contexts;

namespace Parking.DataAccess.Migrations
{
    [DbContext(typeof(ParkingContext))]
    [Migration("20191123171039_initDB")]
    partial class initDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Parking.Domain.Entities.ParkingRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Hours")
                        .HasColumnType("int");

                    b.Property<int>("IsUsed")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("ParkingRates");
                });

            modelBuilder.Entity("Parking.Domain.Entities.ParkingRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CreatedById")
                        .HasColumnType("int");

                    b.Property<string>("LicensePlate")
                        .HasColumnType("nvarchar(10)")
                        .HasMaxLength(10);

                    b.Property<int>("ProvinceCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("Timein")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Timeout")
                        .HasColumnType("datetime2");

                    b.Property<double>("TotalPrice")
                        .HasColumnType("float");

                    b.Property<int?>("UpdatedById")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedById");

                    b.HasIndex("ProvinceCode");

                    b.HasIndex("UpdatedById");

                    b.ToTable("ParkingRecords");
                });

            modelBuilder.Entity("Parking.Domain.Entities.Province", b =>
                {
                    b.Property<int>("ProvinceCode")
                        .HasColumnType("int");

                    b.Property<string>("ProvinceName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("ProvinceCode");

                    b.ToTable("Provinces");

                    b.HasData(
                        new
                        {
                            ProvinceCode = 10,
                            ProvinceName = "กรุงเทพมหานคร"
                        },
                        new
                        {
                            ProvinceCode = 11,
                            ProvinceName = "สมุทรปราการ"
                        },
                        new
                        {
                            ProvinceCode = 12,
                            ProvinceName = "นนทบุรี"
                        },
                        new
                        {
                            ProvinceCode = 13,
                            ProvinceName = "ปทุมธานี"
                        },
                        new
                        {
                            ProvinceCode = 14,
                            ProvinceName = "พระนครศรีอยุธยา"
                        },
                        new
                        {
                            ProvinceCode = 15,
                            ProvinceName = "อ่างทอง"
                        },
                        new
                        {
                            ProvinceCode = 16,
                            ProvinceName = "ลพบุรี"
                        },
                        new
                        {
                            ProvinceCode = 17,
                            ProvinceName = "สิงห์บุรี"
                        },
                        new
                        {
                            ProvinceCode = 18,
                            ProvinceName = "ชัยนาท"
                        },
                        new
                        {
                            ProvinceCode = 19,
                            ProvinceName = "สระบุรี"
                        },
                        new
                        {
                            ProvinceCode = 20,
                            ProvinceName = "ชลบุรี"
                        },
                        new
                        {
                            ProvinceCode = 21,
                            ProvinceName = "ระยอง"
                        },
                        new
                        {
                            ProvinceCode = 22,
                            ProvinceName = "จันทบุรี"
                        },
                        new
                        {
                            ProvinceCode = 23,
                            ProvinceName = "ตราด"
                        },
                        new
                        {
                            ProvinceCode = 24,
                            ProvinceName = "ฉะเชิงเทรา"
                        },
                        new
                        {
                            ProvinceCode = 25,
                            ProvinceName = "ปราจีนบุรี"
                        },
                        new
                        {
                            ProvinceCode = 26,
                            ProvinceName = "นครนายก"
                        },
                        new
                        {
                            ProvinceCode = 27,
                            ProvinceName = "สระแก้ว"
                        },
                        new
                        {
                            ProvinceCode = 30,
                            ProvinceName = "นครราชสีมา"
                        },
                        new
                        {
                            ProvinceCode = 31,
                            ProvinceName = "บุรีรัมย์"
                        },
                        new
                        {
                            ProvinceCode = 32,
                            ProvinceName = "สุรินทร์"
                        },
                        new
                        {
                            ProvinceCode = 33,
                            ProvinceName = "ศรีสะเกษ"
                        },
                        new
                        {
                            ProvinceCode = 34,
                            ProvinceName = "อุบลราชธานี"
                        },
                        new
                        {
                            ProvinceCode = 35,
                            ProvinceName = "ยโสธร"
                        },
                        new
                        {
                            ProvinceCode = 36,
                            ProvinceName = "ชัยภูมิ"
                        },
                        new
                        {
                            ProvinceCode = 37,
                            ProvinceName = "อำนาจเจริญ"
                        },
                        new
                        {
                            ProvinceCode = 39,
                            ProvinceName = "หนองบัวลำภู"
                        },
                        new
                        {
                            ProvinceCode = 40,
                            ProvinceName = "ขอนแก่น"
                        },
                        new
                        {
                            ProvinceCode = 41,
                            ProvinceName = "อุดรธานี"
                        },
                        new
                        {
                            ProvinceCode = 42,
                            ProvinceName = "เลย"
                        },
                        new
                        {
                            ProvinceCode = 43,
                            ProvinceName = "หนองคาย"
                        },
                        new
                        {
                            ProvinceCode = 44,
                            ProvinceName = "มหาสารคาม"
                        },
                        new
                        {
                            ProvinceCode = 45,
                            ProvinceName = "ร้อยเอ็ด"
                        },
                        new
                        {
                            ProvinceCode = 46,
                            ProvinceName = "กาฬสินธุ์"
                        },
                        new
                        {
                            ProvinceCode = 47,
                            ProvinceName = "สกลนคร"
                        },
                        new
                        {
                            ProvinceCode = 48,
                            ProvinceName = "นครพนม"
                        },
                        new
                        {
                            ProvinceCode = 49,
                            ProvinceName = "มุกดาหาร"
                        },
                        new
                        {
                            ProvinceCode = 50,
                            ProvinceName = "เชียงใหม่"
                        },
                        new
                        {
                            ProvinceCode = 51,
                            ProvinceName = "ลำพูน"
                        },
                        new
                        {
                            ProvinceCode = 52,
                            ProvinceName = "ลำปาง"
                        },
                        new
                        {
                            ProvinceCode = 53,
                            ProvinceName = "อุตรดิตถ์"
                        },
                        new
                        {
                            ProvinceCode = 54,
                            ProvinceName = "แพร่"
                        },
                        new
                        {
                            ProvinceCode = 55,
                            ProvinceName = "น่าน"
                        },
                        new
                        {
                            ProvinceCode = 56,
                            ProvinceName = "พะเยา"
                        },
                        new
                        {
                            ProvinceCode = 57,
                            ProvinceName = "เชียงราย"
                        },
                        new
                        {
                            ProvinceCode = 58,
                            ProvinceName = "แม่ฮ่องสอน"
                        },
                        new
                        {
                            ProvinceCode = 60,
                            ProvinceName = "นครสวรรค์"
                        },
                        new
                        {
                            ProvinceCode = 61,
                            ProvinceName = "อุทัยธานี"
                        },
                        new
                        {
                            ProvinceCode = 62,
                            ProvinceName = "กำแพงเพชร"
                        },
                        new
                        {
                            ProvinceCode = 63,
                            ProvinceName = "ตาก"
                        },
                        new
                        {
                            ProvinceCode = 64,
                            ProvinceName = "สุโขทัย"
                        },
                        new
                        {
                            ProvinceCode = 65,
                            ProvinceName = "พิษณุโลก"
                        },
                        new
                        {
                            ProvinceCode = 66,
                            ProvinceName = "พิจิตร"
                        },
                        new
                        {
                            ProvinceCode = 67,
                            ProvinceName = "เพชรบูรณ์"
                        },
                        new
                        {
                            ProvinceCode = 70,
                            ProvinceName = "ราชบุรี"
                        },
                        new
                        {
                            ProvinceCode = 71,
                            ProvinceName = "กาญจนบุรี"
                        },
                        new
                        {
                            ProvinceCode = 72,
                            ProvinceName = "สุพรรณบุรี"
                        },
                        new
                        {
                            ProvinceCode = 73,
                            ProvinceName = "นครปฐม"
                        },
                        new
                        {
                            ProvinceCode = 74,
                            ProvinceName = "สมุทรสาคร"
                        },
                        new
                        {
                            ProvinceCode = 75,
                            ProvinceName = "สมุทรสงคราม"
                        },
                        new
                        {
                            ProvinceCode = 76,
                            ProvinceName = "เพชรบุรี"
                        },
                        new
                        {
                            ProvinceCode = 77,
                            ProvinceName = "ประจวบคีรีขันธ์"
                        },
                        new
                        {
                            ProvinceCode = 80,
                            ProvinceName = "นครศรีธรรมราช"
                        },
                        new
                        {
                            ProvinceCode = 81,
                            ProvinceName = "กระบี่"
                        },
                        new
                        {
                            ProvinceCode = 82,
                            ProvinceName = "พังงา"
                        },
                        new
                        {
                            ProvinceCode = 83,
                            ProvinceName = "ภูเก็ต"
                        },
                        new
                        {
                            ProvinceCode = 84,
                            ProvinceName = "สุราษฎร์ธานี"
                        },
                        new
                        {
                            ProvinceCode = 85,
                            ProvinceName = "ระนอง"
                        },
                        new
                        {
                            ProvinceCode = 86,
                            ProvinceName = "ชุมพร"
                        },
                        new
                        {
                            ProvinceCode = 90,
                            ProvinceName = "สงขลา"
                        },
                        new
                        {
                            ProvinceCode = 91,
                            ProvinceName = "สตูล"
                        },
                        new
                        {
                            ProvinceCode = 92,
                            ProvinceName = "ตรัง"
                        },
                        new
                        {
                            ProvinceCode = 93,
                            ProvinceName = "พัทลุง"
                        },
                        new
                        {
                            ProvinceCode = 94,
                            ProvinceName = "ปัตตานี"
                        },
                        new
                        {
                            ProvinceCode = 95,
                            ProvinceName = "ยะลา"
                        },
                        new
                        {
                            ProvinceCode = 96,
                            ProvinceName = "นราธิวาส"
                        },
                        new
                        {
                            ProvinceCode = 97,
                            ProvinceName = "บึงกาฬ"
                        });
                });

            modelBuilder.Entity("Parking.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ActiveStatus")
                        .HasColumnType("int");

                    b.Property<bool>("IsAdministrator")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(150)")
                        .HasMaxLength(150);

                    b.Property<string>("Salt")
                        .HasColumnType("nvarchar(20)")
                        .HasMaxLength(20);

                    b.Property<DateTime?>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(50)")
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Parking.Domain.Entities.ParkingRecord", b =>
                {
                    b.HasOne("Parking.Domain.Entities.User", "CreatedBy")
                        .WithMany("ParkingRecordCretedBy")
                        .HasForeignKey("CreatedById");

                    b.HasOne("Parking.Domain.Entities.Province", "Province")
                        .WithMany("ParkingRecords")
                        .HasForeignKey("ProvinceCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Parking.Domain.Entities.User", "UpdatedBy")
                        .WithMany("ParkingRecordUpdatedBy")
                        .HasForeignKey("UpdatedById");
                });
#pragma warning restore 612, 618
        }
    }
}
